POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzg4MDExOTgyLCJ1c2VySWQiOjJ9.vQGw8f3J0syuzS76AHzGBNrKpcrcqCWV5beWimw89yE

{
    "name": "Test event",
    "description": "Test event!!!",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}